export interface Manifest {
  Response: Response
  ErrorCode: number
  ThrottleSeconds: number
  ErrorStatus: string
  Message: string
  MessageData: MessageData
}

export interface Response {
  version: string
  mobileAssetContentPath: string
  mobileGearAssetDataBases: MobileGearAssetDataBase[]
  mobileWorldContentPaths: MobileWorldContentPaths
  jsonWorldContentPaths: JsonWorldContentPaths
  jsonWorldComponentContentPaths: JsonWorldComponentContentPaths
  mobileClanBannerDatabasePath: string
  mobileGearCDN: MobileGearCdn
  iconImagePyramidInfo: any[]
}

export interface MobileGearAssetDataBase {
  version: number
  path: string
}

export interface MobileWorldContentPaths {
  en: string
  fr: string
  es: string
  "es-mx": string
  de: string
  it: string
  ja: string
  "pt-br": string
  ru: string
  pl: string
  ko: string
  "zh-cht": string
  "zh-chs": string
}

export interface JsonWorldContentPaths {
  en: string
  fr: string
  es: string
  "es-mx": string
  de: string
  it: string
  ja: string
  "pt-br": string
  ru: string
  pl: string
  ko: string
  "zh-cht": string
  "zh-chs": string
}

export interface JsonWorldComponentContentPaths {
  en: En
  fr: Fr
  es: Es
  "es-mx": EsMx
  de: De
  it: It
  ja: Ja
  "pt-br": PtBr
  ru: Ru
  pl: Pl
  ko: Ko
  "zh-cht": ZhCht
  "zh-chs": ZhChs
}

export interface En {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface Fr {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface Es {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface EsMx {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface De {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface It {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface Ja {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface PtBr {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface Ru {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface Pl {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface Ko {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface ZhCht {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface ZhChs {
  DestinyArtDyeChannelDefinition: string
  DestinyArtDyeReferenceDefinition: string
  DestinyPlaceDefinition: string
  DestinyActivityDefinition: string
  DestinyActivityTypeDefinition: string
  DestinyClassDefinition: string
  DestinyGenderDefinition: string
  DestinyInventoryBucketDefinition: string
  DestinyRaceDefinition: string
  DestinyUnlockDefinition: string
  DestinyStatGroupDefinition: string
  DestinyProgressionMappingDefinition: string
  DestinyFactionDefinition: string
  DestinyVendorGroupDefinition: string
  DestinyRewardSourceDefinition: string
  DestinyUnlockValueDefinition: string
  DestinyRewardMappingDefinition: string
  DestinyRewardSheetDefinition: string
  DestinyItemCategoryDefinition: string
  DestinyDamageTypeDefinition: string
  DestinyActivityModeDefinition: string
  DestinyMedalTierDefinition: string
  DestinyAchievementDefinition: string
  DestinyActivityGraphDefinition: string
  DestinyActivityInteractableDefinition: string
  DestinyBondDefinition: string
  DestinyCharacterCustomizationCategoryDefinition: string
  DestinyCharacterCustomizationOptionDefinition: string
  DestinyCollectibleDefinition: string
  DestinyDestinationDefinition: string
  DestinyEntitlementOfferDefinition: string
  DestinyEquipmentSlotDefinition: string
  DestinyEventCardDefinition: string
  DestinyFireteamFinderActivityGraphDefinition: string
  DestinyFireteamFinderActivitySetDefinition: string
  DestinyFireteamFinderLabelDefinition: string
  DestinyFireteamFinderLabelGroupDefinition: string
  DestinyFireteamFinderOptionDefinition: string
  DestinyFireteamFinderOptionGroupDefinition: string
  DestinyStatDefinition: string
  DestinyInventoryItemDefinition: string
  DestinyInventoryItemLiteDefinition: string
  DestinyItemTierTypeDefinition: string
  DestinyLoadoutColorDefinition: string
  DestinyLoadoutIconDefinition: string
  DestinyLoadoutNameDefinition: string
  DestinyLocationDefinition: string
  DestinyLoreDefinition: string
  DestinyMaterialRequirementSetDefinition: string
  DestinyMetricDefinition: string
  DestinyObjectiveDefinition: string
  DestinySandboxPerkDefinition: string
  DestinyPlatformBucketMappingDefinition: string
  DestinyPlugSetDefinition: string
  DestinyPowerCapDefinition: string
  DestinyPresentationNodeDefinition: string
  DestinyProgressionDefinition: string
  DestinyProgressionLevelRequirementDefinition: string
  DestinyRecordDefinition: string
  DestinyRewardAdjusterPointerDefinition: string
  DestinyRewardAdjusterProgressionMapDefinition: string
  DestinyRewardItemListDefinition: string
  DestinySackRewardItemListDefinition: string
  DestinySandboxPatternDefinition: string
  DestinySeasonDefinition: string
  DestinySeasonPassDefinition: string
  DestinySocialCommendationDefinition: string
  DestinySocketCategoryDefinition: string
  DestinySocketTypeDefinition: string
  DestinyTraitDefinition: string
  DestinyUnlockCountMappingDefinition: string
  DestinyUnlockEventDefinition: string
  DestinyUnlockExpressionMappingDefinition: string
  DestinyVendorDefinition: string
  DestinyMilestoneDefinition: string
  DestinyActivityModifierDefinition: string
  DestinyReportReasonCategoryDefinition: string
  DestinyArtifactDefinition: string
  DestinyBreakerTypeDefinition: string
  DestinyChecklistDefinition: string
  DestinyEnergyTypeDefinition: string
  DestinySocialCommendationNodeDefinition: string
  DestinyGuardianRankDefinition: string
  DestinyGuardianRankConstantsDefinition: string
  DestinyLoadoutConstantsDefinition: string
  DestinyFireteamFinderConstantsDefinition: string
  DestinyGlobalConstantsDefinition: string
}

export interface MobileGearCdn {
  Geometry: string
  Texture: string
  PlateRegion: string
  Gear: string
  Shader: string
}

export interface MessageData {}
